### ISSUE TITLE
How do I access the request headers 

### ISSUE THREAD

**Issue by moadennagi** [digitalocean/sample-functions-python-jokes#10]
There is no indication in the docs on how to access the request context, I need to access the headers

**Comment by rabbah** [comment]
An upcoming docs update will document this. Sorry for the docs gap.
The incoming functions argument has a field called `http` which you can access and it has the `headers`. Here's an example of what it could look like:

```
    "http": {
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip",
        "content-type": "application/json",
        "user-agent": "curl/7.81.0",
        "x-request-id": "edf7f8c2799e014daa7ed29c8b615a6f"
      },
      "method": "POST",
      "path": ""
    },
```

**Comment by moadennagi** [comment]
Thanks @rabbah . Looking forward for more documentation.
