### ISSUE TITLE
This exact example fails after deployment...

### ISSUE THREAD

**Issue by dcshapiro** [digitalocean/sample-functions-python-jokes#2]
[
  "2022-05-24T23:25:33.193682267Z stderr: 2022/05/24 23:25:33 symlink /usr/lib/python2.7/UserDict.py action/1/src/virtualenv/local/lib/python2.7/UserDict.py: no such file or directory",
  "2022-05-24T23:25:33.919383133Z stderr: 2022/05/24 23:25:33 symlink /usr/lib/python2.7/UserDict.py action/1/src/virtualenv/lib/python2.7/UserDict.py: no such file or directory",
  "2022-05-24T23:25:35.150471087Z stderr: Traceback (most recent call last):",
  "2022-05-24T23:25:35.150501367Z stderr:   File \"/tmp/action/1/bin/exec__.py\", line 46, in <module>",
  "2022-05-24T23:25:35.150809032Z stderr:     from main__ import main as main",
  "2022-05-24T23:25:35.150855853Z stderr:   File \"/tmp/action/1/bin/main__.py\", line 1, in <module>",
  "2022-05-24T23:25:35.151199317Z stderr:     import pyjokes",
  "2022-05-24T23:25:35.151210453Z stderr: ModuleNotFoundError: No module named 'pyjokes'",
  "2022-05-24T23:25:35.46728098Z  stderr: Command exited abruptly during initialization.",
  "2022-05-24T23:25:35.469134Z    stderr: The action did not initialize or run as expected. Log data might be missing."
]

**Comment by dcshapiro** [comment]
perhaps the wrong python is being used in the backend?

**Comment by rabbah** [comment]
Hey Dan. I think you're deploying this project with the CLI and you have `python:2.7` available. The project requires 3+. You can overcome this with a remote build as follows.

```
> doctl serverless deploy . --remote-build
Deploying 'sample-functions-python-jokes'
  to namespace 'fn-...'
  on host 'https://faas-...'
Submitted action 'joke' for remote building and deployment in runtime python:default (id: 0ba0834f521b4f5ca0834f521b4f5c53)
Processing of 'joke' is still running remotely ...
...
Deployed functions ('doctl sbx fn get <funcName> --url' for URL):
  - joke
```

```
> doctl serverless functions invoke joke
{
  "body": {
    "response_type": "in_channel",
    "text": "Waiter: He's choking! Is anyone a doctor? Programmer: I'm a Vim user."
  }
}
```

Note the CLI command can be abbreviated as `doctl sls fn invoke joke`. We'll update the README.
By adding `--remote-build` to the deploy step, you ensure the build and runtime environments match.

**Comment by dcshapiro** [comment]
Thanks. I will try this.

**Comment by dcshapiro** [comment]
I confirm it is working now. Very few imports succeed to compile because of memory and storage limits, but this is expected.

Thank you,

Daniel
