### ISSUE TITLE
Any way to define the HTML method?

### ISSUE THREAD

**Issue by xandrade** [digitalocean/sample-functions-python-jokes#4]
I'm super happy for the release of Functions. Just wondering if it is possible to include other HTML methods like POST.
So far, the two toy demos ([sample-functions-python-jokes](https://github.com/digitalocean/sample-functions-python-jokes) and https://github.com/digitalocean/sample-functions-python-helloworld) are not enough.

**Comment by rabbah** [comment]
Thanks for the feedback. Here’s an example which can provide more details https://github.com/digitalocean/sample-functions-apollo-graphql/blob/main/packages/default/graphql/ApolloServer.ts. The variable __ow_method is available in the functions arguments and may be used to dispatch on the HTTP method. Some more useful info is here https://www.digitalocean.com/community/questions/functions-how-to-access-request-info-return-other-response-types
